before_install:
  - gem install activesupport -v "4.2.6"
  - gem install cocoapods -v "0.39.0"
  - brew update
  - if brew outdated | grep -qx xctool; then brew upgrade xctool; fi

language: objective-c

xcode_workspace: PAYFormBuilder.xcworkspace
xcode_scheme: Example
xcode_sdk: iphonesimulator

script: 
    - "xctool -workspace PAYFormBuilder.xcworkspace -scheme Example -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.1' build test"
